### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rohittp0**

### CODE REVIEW

**Comment by rohittp0** [comment]
Login not working

https://saturday-hack-night--pr5-dev-11m1c8f7.web.app/

**Comment by DarkPhoenix2704** [comment]
[268e486](https://github.com/tinkerhub/saturday-hack-night/pull/5/commits/268e48c52b0e023024a14c8a425a79fd186d4e50) Fixes the issue

**Comment by rohittp0** [comment]
**',' is not removed**

image

When the user types in a username and then adds a, it should spill the names based on the ',' and remove it.

image

Typing in multiple names should work

**Comment by rohittp0** [comment]
**Use HTML Form Errors**

image

Instead of showing errors using a popup show the error under the text box itself ( Default form behaviour )

**Comment by rohittp0** [comment]
**User login is not mandatory to see upcoming events**

**Comment by rohittp0** [comment]
There should be some way for the user to navigate back from this page 
image
 And proper error message is also required

**Comment by DarkPhoenix2704** [comment]
> **User login is not mandatory to see upcoming events**

Currently the events is inside the dashboard Component , which requires authentication.
So have to refactor a lot

**Comment by DarkPhoenix2704** [comment]
## TODO

- [x] Fix Events Styling
- [x] ~Clicking on Dashboard does Nothing when not logged in~ Opens AuthPopUp
- [x] ~Enable Navigation in Join page~ Added Button to go to home page
- [x] ~Show error message in Join Page~ Shows error Description
- [ ] Issues in Memberchips Component
- [ ] Use HTML Form Errors

**Pull request merged**
