### PR TITLE
feat(web): added jest testing support , restructured folders  in web codebase

### PR DESCRIPTION
**Pull request by sreehari2003**
added jest as testing library and added folder structres for testing with a basic test case

### CODE REVIEW

**Comment by DarkPhoenix2704** [comment]
@sreehari2003 add actions for running test

**Comment by sreehari2003** [comment]
> @sreehari2003 add actions for running test

is this workflow enough ?

**Comment by sreehari2003** [comment]
> > @sreehari2003 add actions for running test
> 
> is this workflow enough ?

@DarkPhoenix2704  need a review

**Comment by sreehari2003** [comment]
@DarkPhoenix2704  code looks good now all test cases passing and files are more structured now

**Review by DarkPhoenix2704 — APPROVED** [review]
LGTM!

**Pull request merged**
